import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {Football} from "@/components/UI/Football";
import {FileUploader} from "@/components/UI/FileUploader/FileUploader";

export default function Image() {
    return (
        <>
            <Head>
                <title>File Uploader</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <FileUploader />
            </main>
        </>
    )
}