import Head from "next/head";
import {VideoPlayer} from "@/components/UI/VideoPlayer/VideoPlayer";

export default function Video () {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <VideoPlayer />
            </main>
        </>

    )
}